import type { Course } from "./types"

export const SEED_SPECIALTY_ITEMS: Course[] = [
  {
    id: 101,
    title: "완도 건조 미역 선물세트",
    region: "전남 완도",
    category: "해조류",
    categoryType: "특산품",
    description: "청정 완도 바다에서 자란 미역을 정성껏 건조한 프리미엄 선물세트",
    image: "/seed-images/specialty/seaweed.svg",
    days: 0,
    price: { total: 28000 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 189,
    rating: 4.8,
    comments: 34,
    halalCertified: true,
    officialCertified: true,
    author: "완도어촌계",
    hashtags: ["#완도미역", "#해조류", "#선물세트", "#청정바다", "#특산품"],
    detailedDescription:
      "완도 청정 해역에서 자란 미역을 정성껏 건조한 프리미엄 선물세트입니다.\n\n겨울철 찬 바닷물에서 자란 미역은 영양가가 풍부하고 식감이 쫄깃합니다.",
    createdAt: "2024-02-10",
  },
  {
    id: 102,
    title: "안성 청정 한우 육포",
    region: "경기 안성",
    category: "간식",
    categoryType: "특산품",
    description: "안성 청정지역에서 키운 한우로 만든 프리미엄 육포",
    image: "/seed-images/specialty/jerky.svg",
    days: 0,
    price: { total: 16500 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 234,
    rating: 4.7,
    comments: 45,
    halalCertified: false,
    officialCertified: true,
    author: "안성축산농가",
    hashtags: ["#안성한우", "#육포", "#간식", "#로컬푸드", "#특산품"],
    detailedDescription: "안성 청정지역에서 키운 한우로 만든 프리미엄 육포입니다.",
    createdAt: "2024-02-15",
  },
  {
    id: 103,
    title: "담양 대나무 죽순 절임",
    region: "전남 담양",
    category: "농산물",
    categoryType: "특산품",
    description: "담양 죽녹원 인근에서 재배한 신선한 죽순을 전통 방식으로 절인 제품",
    image: "/seed-images/specialty/doenjang.svg",
    days: 0,
    price: { total: 14000 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 145,
    rating: 4.6,
    comments: 28,
    halalCertified: true,
    officialCertified: true,
    author: "담양농가",
    hashtags: ["#담양죽순", "#절임", "#농산물", "#죽녹원", "#특산품"],
    detailedDescription: "담양 죽녹원 인근에서 재배한 신선한 죽순을 전통 방식으로 절인 제품입니다.",
    createdAt: "2024-02-20",
  },
  {
    id: 104,
    title: "영양 고추 청양고추가루",
    region: "경북 영양",
    category: "양념",
    categoryType: "특산품",
    description: "청정 영양에서 재배한 청양고추를 곱게 간 프리미엄 고추가루",
    image: "/seed-images/specialty/jerky.svg",
    days: 0,
    price: { total: 22000 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 278,
    rating: 4.9,
    comments: 52,
    halalCertified: true,
    officialCertified: true,
    author: "영양고추농가",
    hashtags: ["#영양고추", "#청양고추", "#고추가루", "#양념", "#특산품"],
    detailedDescription: "청정 영양에서 재배한 청양고추를 곱게 간 프리미엄 고추가루입니다.",
    createdAt: "2024-02-12",
  },
  {
    id: 105,
    title: "봉화 송이버섯 건조품",
    region: "경북 봉화",
    category: "농산물",
    categoryType: "특산품",
    description: "봉화 깊은 산속에서 자란 야생 송이버섯을 정성껏 건조한 제품",
    image: "/seed-images/specialty/seaweed.svg",
    days: 0,
    price: { total: 85000 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 167,
    rating: 4.8,
    comments: 31,
    halalCertified: false,
    officialCertified: true,
    author: "봉화산나물농가",
    hashtags: ["#봉화송이", "#송이버섯", "#건조버섯", "#프리미엄", "#특산품"],
    detailedDescription: "봉화 깊은 산속에서 자란 야생 송이버섯을 정성껏 건조한 제품입니다.",
    createdAt: "2024-02-08",
  },
]

export const SEED_GOODS_ITEMS: Course[] = [
  {
    id: 201,
    title: "TRAVEL MAKER 에코백",
    region: "온라인",
    category: "머천다이즈",
    categoryType: "굿즈",
    description: "여행을 사랑하는 당신을 위한 감성 에코백",
    image: "/seed-images/goods/tote.svg",
    days: 0,
    price: { total: 18900 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 412,
    rating: 4.7,
    comments: 78,
    halalCertified: false,
    officialCertified: false,
    author: "TRAVEL MAKER",
    hashtags: ["#에코백", "#굿즈", "#여행", "#토트백", "#머천다이즈"],
    detailedDescription: "여행을 사랑하는 당신을 위한 감성 에코백입니다.",
    createdAt: "2024-02-18",
  },
  {
    id: 202,
    title: "감성 여행 스티커팩",
    region: "온라인",
    category: "문구",
    categoryType: "굿즈",
    description: "로컬 여행의 순간을 기록하는 감성 스티커 모음",
    image: "/seed-images/goods/sticker.svg",
    days: 0,
    price: { total: 6900 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 589,
    rating: 4.9,
    comments: 134,
    halalCertified: false,
    officialCertified: false,
    author: "TRAVEL MAKER",
    hashtags: ["#스티커", "#여행스티커", "#굿즈", "#문구", "#다이어리"],
    detailedDescription: "로컬 여행의 순간을 기록하는 감성 스티커 모음입니다.",
    createdAt: "2024-02-22",
  },
  {
    id: 203,
    title: "로컬 여행 트래블 노트",
    region: "온라인",
    category: "문구",
    categoryType: "굿즈",
    description: "여행 기록을 위한 감성 트래블 노트",
    image: "/seed-images/goods/journal.svg",
    days: 0,
    price: { total: 12500 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 345,
    rating: 4.6,
    comments: 67,
    halalCertified: false,
    officialCertified: false,
    author: "TRAVEL MAKER",
    hashtags: ["#트래블노트", "#여행노트", "#다이어리", "#굿즈", "#기록"],
    detailedDescription: "여행 기록을 위한 감성 트래블 노트입니다.",
    createdAt: "2024-02-16",
  },
  {
    id: 204,
    title: "TRAVEL MAKER 캠핑 머그컵",
    region: "온라인",
    category: "캠핑",
    categoryType: "굿즈",
    description: "여행지에서 사용하기 좋은 스테인리스 머그컵",
    image: "/seed-images/goods/tote.svg",
    days: 0,
    price: { total: 15900 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 267,
    rating: 4.5,
    comments: 48,
    halalCertified: false,
    officialCertified: false,
    author: "TRAVEL MAKER",
    hashtags: ["#머그컵", "#캠핑", "#여행용품", "#굿즈", "#스테인리스"],
    detailedDescription: "여행지에서 사용하기 좋은 스테인리스 머그컵입니다.",
    createdAt: "2024-02-14",
  },
  {
    id: 205,
    title: "로컬 여행 지도 포스터",
    region: "온라인",
    category: "인테리어",
    categoryType: "굿즈",
    description: "한국 로컬 여행지를 담은 감성 지도 포스터",
    image: "/seed-images/goods/journal.svg",
    days: 0,
    price: { total: 24000 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 198,
    rating: 4.8,
    comments: 42,
    halalCertified: false,
    officialCertified: false,
    author: "TRAVEL MAKER",
    hashtags: ["#포스터", "#지도", "#인테리어", "#굿즈", "#여행지도"],
    detailedDescription: "한국 로컬 여행지를 담은 감성 지도 포스터입니다.",
    createdAt: "2024-02-11",
  },
]

export function generateMockItems(categoryType: "특산품" | "굿즈", count = 6): Course[] {
  const now = Date.now()
  const isSpecialty = categoryType === "특산품"

  return Array.from({ length: count }).map((_, i) => ({
    id: Number(`${isSpecialty ? "99" : "98"}${i}${now % 1000}`),
    title: isSpecialty ? `지역 특산 상품 #${i + 1}` : `굿즈 상품 #${i + 1}`,
    region: isSpecialty ? "로컬" : "온라인",
    category: isSpecialty ? "농산물" : "머천다이즈",
    categoryType,
    description: isSpecialty ? "지역 농가에서 직접 생산한 신선한 특산품" : "여행을 더 특별하게 만들어줄 감성 굿즈",
    image: isSpecialty ? "/seed-images/specialty/seaweed.svg" : "/seed-images/goods/tote.svg",
    days: 0,
    price: { total: isSpecialty ? 10000 + i * 1200 : 5000 + i * 800 },
    difficulty: "Easy",
    transportation: [],
    petFriendly: false,
    likes: 50 + i * 7,
    rating: 4.5,
    comments: 3 + i,
    halalCertified: false,
    officialCertified: false,
    author: isSpecialty ? "로컬농가" : "TRAVEL MAKER",
    hashtags: isSpecialty ? ["#특산품", "#로컬"] : ["#굿즈", "#여행"],
    detailedDescription: "",
    createdAt: new Date(Date.now() - i * 86400000).toISOString().split("T")[0],
  }))
}
